### ISSUE TITLE
There are some obvious bugs.

### ISSUE THREAD

**Issue by 18445864529** [sooftware/Speech-Transformer#3]
An unexpected variable 'encoder_logits':
https://github.com/sooftware/speech-transformer/blob/f072dc34585fa6c49a9c0fff86abf8604331a313/speech_transformer/model.py#L128

A nonexistent attribute self.max_length:
https://github.com/sooftware/speech-transformer/blob/f072dc34585fa6c49a9c0fff86abf8604331a313/speech_transformer/decoder.py#L189

Two mismatching keyword arguments:
https://github.com/sooftware/speech-transformer/blob/f072dc34585fa6c49a9c0fff86abf8604331a313/speech_transformer/decoder.py#L140
https://github.com/sooftware/speech-transformer/blob/f072dc34585fa6c49a9c0fff86abf8604331a313/speech_transformer/decoder.py#L142

**Comment by sooftware** [comment]
Thank you for let me know.  
I'll fix it.
